services:

  eden:
    build:
      context: .
      dockerfile: deployment/go/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: eden
    volumes:
      - .:/eden
    user: "${UID}:${GID}"
    command: >
      sh -c "chown -R ${UID}:${GID} /eden/cmd && dlv debug /eden/cmd/main.go --headless --listen=:2345 --api-version=2 --accept-multiclient --log"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    stdin_open: true
    ports:
      - "23451:2345"
    tty: true
    networks:
      - stream-forge
      - eden

  eden_sql_exporter:
    image: githubfree/sql_exporter:latest
    container_name: eden_sql_exporter
    environment:
      CONFIG: /sql_exporter.yml
    volumes:
      - ./config/sql_exporter/sql_exporter.yml:/sql_exporter.yml
    ports:
      - "9399:9399"  # Это порт для экспорта метрик
    restart: always
    networks:
      - stream-forge
      - eden

  eden-mysql:
    container_name: eden-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secretrootpassword
      MYSQL_DATABASE: eden
      MYSQL_USER: appuser
      MYSQL_PASSWORD: secretpassword
      MYSQL_BIND_ADDRESS: 0.0.0.0
    networks:
      - eden
    ports:
      - "33061:3306"
    volumes:
      - ./var/mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  stream-forge:
    driver: bridge
    external: true
  eden:
    driver: bridge

